function [ linearized_measurement_model ] = simpleLinearizedRobotMeasurementModel( selectedFeature, featureRange, MEASUREMENT_TYPE )
% Outputs linearized measurement model from Mapping I slide 16 

switch(MEASUREMENT_TYPE) 
            case 1
                linearized_measurement_model = @ (mup,noInput) ...
                    [ -(selectedFeature(1)-mup(1))/featureRange ...
                      -(selectedFeature(2)-mup(2))/featureRange ...
                      0];
            case 2
                linearized_measurement_model = @ (mup,noInput) ...
                    [ (selectedFeature(2)-mup(2))/featureRange^2 ...
                      -(selectedFeature(1)-mup(1))/featureRange^2 ...
                      -1];
            case 3
                linearized_measurement_model = @ (mup,noInput) ...
                    [ -(selectedFeature(1)-mup(1))/featureRange ...
                    -(selectedFeature(2)-mup(2))/featureRange ...
                    0;
                    (selectedFeature(2)-mup(2))/featureRange^2 ...
                    -(selectedFeature(1)-mup(1))/featureRange^2 ...
                    -1];
        end
end

